config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "welcome#index"
  get 'about_us', to: 'welcome#about_us'
  get 'contact', to: 'welcome#contact'
  resources :posts do
    resources :comments, except: :show
  end
  resources :categories, except: :show

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }

      end
      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/address.rb
module Address
  def self.table_name_prefix
    "address_"
  end
end

app/models/address/barangay.rb
class Address::Barangay < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :city
end

app/models/address/city.rb
class Address::City < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :province
  has_many :barangays
end

app/models/address/province.rb
class Address::Province < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :region
  has_many :cities
end

app/models/address/region.rb
class Address::Region < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  has_many :provinces
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :post_category_ships
  has_many :posts, through: :post_category_ships

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  has_many :comments
  has_many :post_category_ships
  has_many :categories, through: :post_category_ships
end

app/models/post_category_ship.rb
class PostCategoryShip < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/controllers/api/v1/barangays_controller.rb
class Api::V1::BarangaysController < ApplicationController

  def index
    city = Address::City.find_by_id(params[:city_id])
    barangays = if city
                  city.barangays
                else
                  Address::Barangay.all
                end
    render json: barangays
  end

  def show
    barangay = Address::Barangay.find(params[:id])
    render json: barangay
  end
end

app/controllers/api/v1/cities_controller.rb
class Api::V1::CitiesController < ApplicationController

  def index
    province = Address::Province.find_by_id(params[:province_id])
    cities = if province
               province.cities
             else
               Address::City.all
             end

    render json: cities
  end

  def show
    city = Address::City.find(params[:id])
    render json: city
  end
end

app/controllers/api/v1/provinces_controller.rb
class Api::V1::ProvincesController < ApplicationController

  def index
    region = Address::Region.find_by_id(params[:region_id])
    provinces = if region
                  region.provinces
                else
                  Address::Province.all
                end

    render json: provinces
  end

  def show
    province = Address::Province.find_by_id(params[:id])
    render json: province
  end
end

app/controllers/api/v1/regions_controller.rb
class Api::V1::RegionsController < ApplicationController

  def index
    regions = Address::Region.all
    render json: regions
  end

  def show
    region = Address::Region.find(params[:id])
    render json: region
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created successfully'
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category updated successfully'
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Category deleted successfully'
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]


  def index
    @comments = @post.comments
  end

  def new
    @comment = @post.comments.build
  end
    
  def create
    @comment = @post.comments.build(comment_params)
    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end

  def edit; end
  
  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Comment updated successfully'
      redirect_to post_comments_path(@post)
    else
      render :edit
    end
 end

def destroy
  @comment.destroy
  flash[:notice] = 'Comment deleted successfully'
  redirect_to post_comments_path(@post)
end

    
  private

  def set_post
    @post = Post.find params[:post_id]
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.includes(:categories).all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    end
  end

  def show; end

  def edit; end
  
  def update
    if @post.update(post_params)
      redirect_to posts_path
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, category_ids: [])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
  def about_us; end

  def contact; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category, url: path, data: { turbo: false } do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/categories/edit_html.erb
<h1>category id: <%= @category.id %></h1>
<%= render partial: 'form', locals: { category: @category, path: category_path(@category) } %>

app/views/categories/index.html.erb
<h1>Category</h1>
<ul>
    <% @categories.each do |category| %>
        <li>
            <%= category.name %>
            <%= link_to :edit, edit_category_path(category) %>
            <%= button_to :delete, category_path(category), method: :delete %>
        </li>
    <% end %>
</ul>
 
<%= link_to 'new', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render partial: 'form', locals: { category: @category, path: categories_path } %>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: path, data: { turbo: false } do |form| %>
  <% if comment.errors.any? %>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Title: <%= @post.title %></h1>
<h2>Edit Comment ID: <%= @comment.id %></h2>
<%= render partial: 'form', locals: { post: @post, comment: @comment, path: post_comment_path(@post, @comment) } %>

app/views/comments/index.html.erb
<h1>Title <%= @post.title %></h1>
<h2>Comments</h2>
<ul>
<% @comments.each do |comment| %>
<li>
    <%= comment.content %>(<%= comment.created_at %>)
    <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
    <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete %>
</li>
<% end %>
</ul>

<%= link_to 'Post List', posts_path %>
<%= link_to 'New Comment', new_post_comment_path(@post) %>

app/views/comments/new.html.erb
<h1>Title: <%= @post.title %></h1>
<%= render partial: 'form', locals: { post: @post, comment: @comment, path: post_comments_path(@post) } %>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>
  <%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post id: <%= @post.id %></h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Post List</h1>
<%= link_to 'New Post', new_post_path, class: 'btn btn-sm btn-success' %>
<table class = "table table-striped">
  <thead>
  <td>title</td>
  <td>content</td>
  <td>category</td>
  <td>action</td>
  </thead>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= post.categories.pluck(:name).join(',') %></td>
      <td class = "d-flex gap-2">
        <%= button_to 'Delete', post_path(post), method: :delete , class: 'btn btn-sm btn-warning' %>
        <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-sm btn-warning' %>
        <%= link_to 'Show', post_path(post), class: 'btn btn-sm btn-warning' %> 
        <%= link_to 'Comments', post_comments_path(post), class: 'btn btn-sm btn-warning'  %>
      </td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>show post id: <%= @post.id %></h1>
<ul>
  <li><%= @post.title %></li>
  <li><%= @post.content %></li>
</ul>